<?php

namespace DoctrineORMModule\Proxy\__CG__\Person\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Person extends \Person\Model\Person implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'name', 'businessName', 'identification', 'stateCode', 'cityCode', 'site', 'image', 'contactPerson', 'observation', 'alert', 'active', 'creditLimit', 'isClient', 'isSupplier', 'flowCollection', 'emailCollection', 'client', 'clientData', 'personType', 'activity', 'phoneCollection', 'addressCollection', 'productCollection', 'deliveredTradeCollection', 'tradeCollection', 'id', 'created', 'updated', 'inputFilter');
        }

        return array('__isInitialized__', 'name', 'businessName', 'identification', 'stateCode', 'cityCode', 'site', 'image', 'contactPerson', 'observation', 'alert', 'active', 'creditLimit', 'isClient', 'isSupplier', 'flowCollection', 'emailCollection', 'client', 'clientData', 'personType', 'activity', 'phoneCollection', 'addressCollection', 'productCollection', 'deliveredTradeCollection', 'tradeCollection', 'id', 'created', 'updated', 'inputFilter');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Person $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function addDeliveredTrade(\Inventory\Model\Trade $deliveredTrade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDeliveredTrade', array($deliveredTrade));

        return parent::addDeliveredTrade($deliveredTrade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveredTradeCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveredTradeCollection', array());

        return parent::getDeliveredTradeCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function addTrade(\Inventory\Model\Trade $trade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTrade', array($trade));

        return parent::addTrade($trade);
    }

    /**
     * {@inheritDoc}
     */
    public function getTradeCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTradeCollection', array());

        return parent::getTradeCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\Inventory\Model\Product $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', array($product));

        return parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductCollection', array());

        return parent::getProductCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function addAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAddress', array($address));

        return parent::addAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressCollection($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressCollection', array($address));

        return parent::setAddressCollection($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressCollection', array());

        return parent::getAddressCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmail', array($email));

        return parent::addEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCollection($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCollection', array($email));

        return parent::setEmailCollection($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCollection', array());

        return parent::getEmailCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', array());

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivity($activity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivity', array($activity));

        return parent::setActivity($activity);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivity', array());

        return parent::getActivity();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlert($alert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlert', array($alert));

        return parent::setAlert($alert);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlert', array());

        return parent::getAlert();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessName($businessName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessName', array($businessName));

        return parent::setBusinessName($businessName);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessName', array());

        return parent::getBusinessName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCityCode($cityCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCityCode', array($cityCode));

        return parent::setCityCode($cityCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCityCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCityCode', array());

        return parent::getCityCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientData($clientData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientData', array($clientData));

        return parent::setClientData($clientData);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientData', array());

        return parent::getClientData();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPerson($contactPerson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPerson', array($contactPerson));

        return parent::setContactPerson($contactPerson);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPerson', array());

        return parent::getContactPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreditLimit($creditLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreditLimit', array($creditLimit));

        return parent::setCreditLimit($creditLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditLimit', array());

        return parent::getCreditLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function addFlow($flow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFlow', array($flow));

        return parent::addFlow($flow);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlowCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlowCollection', array());

        return parent::getFlowCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentification($identification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentification', array($identification));

        return parent::setIdentification($identification);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentification', array());

        return parent::getIdentification();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsClient($isClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsClient', array($isClient));

        return parent::setIsClient($isClient);
    }

    /**
     * {@inheritDoc}
     */
    public function isClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isClient', array());

        return parent::isClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsSupplier($isSupplier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsSupplier', array($isSupplier));

        return parent::setIsSupplier($isSupplier);
    }

    /**
     * {@inheritDoc}
     */
    public function isSupplier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSupplier', array());

        return parent::isSupplier();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation($observation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', array($observation));

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', array());

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonType($personType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonType', array($personType));

        return parent::setPersonType($personType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonType', array());

        return parent::getPersonType();
    }

    /**
     * {@inheritDoc}
     */
    public function addPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPhone', array($phone));

        return parent::addPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneCollection($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneCollection', array($phone));

        return parent::setPhoneCollection($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneCollection', array());

        return parent::getPhoneCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function setSite($site)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSite', array($site));

        return parent::setSite($site);
    }

    /**
     * {@inheritDoc}
     */
    public function getSite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSite', array());

        return parent::getSite();
    }

    /**
     * {@inheritDoc}
     */
    public function setStateCode($stateCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStateCode', array($stateCode));

        return parent::setStateCode($stateCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getStateCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStateCode', array());

        return parent::getStateCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function exchangeArray($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'exchangeArray', array($data));

        return parent::exchangeArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCopy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCopy', array());

        return parent::getArrayCopy();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
